/*
document.write("<TABLE border='0' cellpadding='1' cellspacing='0' bgcolor='#000000'><TR> <TD width='100%'><TABLE width='100%' border='0' cellpadding='3' cellspacing='0' bgcolor='#000000'>");
document.write("  <TR> <TD bgcolor='#000000' valign='top' width='100%'><A HREF='http://rhizome.org/netartnews' target='_window'><img src='http://rhizome.org/baseims/button_nanlogoblack.gif' border='0' alt='RHIZOME.ORG -> NET ART NEWS'></a></td></tr>");
document.write("  <TR> <TD bgcolor='#EEEEEE' valign='top' width='100%'>");
document.write("   <a href='http://www.drunkenboat.com/db7/index.html' target='_window'><font color='#000000' face='arial,helvetica,sans-serif'><b>WHY ART NEEDS A HOLE IN THE HEAD</b></font></a><br><img src='http://rhizome.org/baseims/spacer.gif' width='100' height='4'><br>");
document.write("   <a href='http://www.drunkenboat.com/db7/index.html' target='_window'><img src='http://rhizome.org/imagebase/netartnews/20050318_thumbnail.gif' align='left' border='0'></a>");
document.write("   <font color='#000000' size='-2'>MARCH 18, 2005</font><font color='#000000'> &#151; Since 2000, the online journal Drunken Boat has been describing wayward contours through an intermedia landscape at least as strange as the one evoked by the 'Bateau ivre' of French poet Arthur Rimbaud. Issue #7 is dedicated to the neurological condition 'aphasia' and those whom it afflicts and inspires. It is the Drunken Boat's editors' contention that aphasia, a result of the brain's inability to match sensory input and linguistic expression, has the potential to realign the way we think about creativity. There is an ensemble of approaches to the subject, sometimes tangential, at times personal and head-on, from poets, essayists, film-makers, sound artists, and an opera singer. Sound files, text works, images and videos abound. Digital artist Christina McPhee's Aphasia + Parrhesia figures a link between neural nets and the internet via the cyborg body and the metaphor of access to/denial of speech. Drunken Boat's excursus into the murky terrain of brain disorder eschews pathos and 'idiot savant' triumphalism alike. Instead, it opens up the sealed circuit of silence and fear to a rich and skewed speech at the borders of the possible. - Marina Vishmidt</font><br>");
document.write("   <A HREF='http://rhizome.org/netartnews' target='_window'><img src='http://rhizome.org/baseims/button_nanmorenews.gif' border='0' alt='MORE NEWS'></A><A HREF='http://rhizome.org/netartnews/subscribe.php' target='_window'><img src='http://rhizome.org/baseims/button_nansubscribe.gif' border='0' alt='SUBSCRIBE'></A></td></tr>");
document.write("</table></td></tr></table>");
*/

// my code
document.write("<TABLE border='0' cellpadding='1' cellspacing='0'><TR> <TD width='100%'> RHIZOME.ORG -> NET ART NEWS <BR> NOT WORKING AT THIS POINT </TD></TR></TABLE>");
