var lines = ['Starting boot sequence. ',
'-1 ',
'loading kernel ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-15 ',
'+ checking integrity ',
'-15 ',
'Linux version 4.6.18-5-686 (gcc version 8.1.2) ',
'-15 ',
'BIOS-provided physical RAM map: ',
' BIOS-e820: 0000000000000000 - 000000000009fc00 (usable) ',
' BIOS-e820: 000000000009fc00 - 00000000000a0000 (reserved) ',
' BIOS-e820: 00000000000f0000 - 0000000000100000 (reserved) ',
' BIOS-e820: 0000000000100000 - 000000001f7f0000 (usable) ',
' BIOS-e820: 000000001f7f0000 - 000000001f7f3000 (ACPI NVS) ',
' BIOS-e820: 000000001f7f3000 - 000000001f800000 (ACPI data) ',
' BIOS-e820: 000000001f800000 - 0000000019000000 (reserved) ',
' BIOS-e820: 00000000fec00000 - 0000000100000000 (reserved) ',
'-1 ',
'Detecting hardware: ',
'-1 ',
'6144MB HIGHMEM available. ',
'512MB LOWMEM available. ',
'-1 ',
'BODY FOUND, CONNECTION FOUND. ',
'-15 ',
'Full body analysis. ',
'-30 ',
'Loading drivers and simulation handlers: ',
'-15 ',
'+ internal organs, ',
'-15 ',
'+ skin, ',
'-15 ',
'+ head, ',
'-15 ',
'+ neck, ',
'-15 ',
'+ arms, ',
'-15 ',
'+ legs. ',
'-60 ',
'dhcdbd: Started up. ',
'-1 ',
'dhcdbd: starting (version 2.16.1), pid 2813 user \'root\' ',
'-1 ',
'dhcdbd: Resolved address "xml:readonly:/etc/gconf/gconf.xml.mandatory" to a read-only configuration source at position 0 ',
'-1 ',
'NetworkManager: ^Istarting... ',
'-1 ',
'NetworkManager: ^Ieth0: Device is fully-supported using driver \'8139too\'. ',
'-1 ',
'NetworkManager: ^Inm_device_init(): device\'s worker thread started, continuing. ',
'-1 ',
'NetworkManager: ^IUpdating allowed wireless network lists. ',
'-1 ',
'Establishing connections. ',
'-60 ',
'Downloading dictionaries. ',
'-60 ',
'Found Spanish language. ',
'-60 ',
'Building language associations ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-30 ',
'Building conscience data ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-30 ',
'AWARENESS ACHIEVE AT Jun 1 00:47:00 UTC 2237 ',
'-140 ',
'Stand by... ',
'-140 ',
'Stand by... ',
'-140 ',
'Stand by... ',
'-30 ',
'Getting set of instructions. ',
'-30 ',
'Opening console. ',
'-5 ',
'login: ',
'-15 ',
'+ root ',
'-15 ',
'password: ',
'-60 ',
'Welcome to internal GNU/linux console ',
'Bash$ ',
'-220 ',
'+ question "Cuál es tu nombre?" ',
'-15 ',
'Generating random name ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-15 ',
'echo "Peter Doe." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Conoces las reglas del juego, Peter?" ',
'-15 ',
'echo "Sí." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ verbose-reply ',
'-15 ',
'echo "Estoy sólo en un cuarto. El interrogador está afuera. Debo responder a sus preguntas." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ quetion "Entiendes por qué se realiza este ejercicio?" ',
'-10 ',
'bash: Bad command or name file ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Entiendes por qué se realiza este ejercicio?" ',
'-15 ',
'Reading manual ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'echo "Se trata del test de Turin. Hay varios cuartos como este en el que estoy. Dentro de cada uno puede haber una maquina o un hombre. El interrogador nos hace las mismas preguntas a cada uno. Debe determinar, guiándose solamente por las respuestas, quién es un hombre y quién es una maquina." ',
'-15 ',
'Bash$ ',
'-120 ',
'+ exit ',
'-5 ',
' ',
'login: ',
'-15 ',
'+ user ',
'-15 ',
'password: ',
'-80 ',
'Welcome to internal GNU/linux console ',
'Bash$ ',
'-220 ',
'+ question "Buenas tardes. ¿Cuál es tu nombre?" ',
'-15 ',
'echo "Buenas. Mi nombre es Peter." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Qué coincidencia, tengo un sobrino que se llama Peter." ',
'-15 ',
'echo "Me pusieron así por mi padre." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Eres bueno con las matemáticas, Peter?" ',
'-15 ',
'echo "Sí, solía ir a concursos cuando era un niño." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Cuál es la raíz cuadrada de 31?" ',
'-15 ',
'echo "Entre 5 y 6. Necesitaría una calculadora para responder eso." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "A menos que seas una computadora, ¿no?" ',
'-15 ',
'echo "Quizás deberías hacer esa pregunta en la puerta de al lado." ',
'-140 ',
'Stand by... ',
'-140 ',
'Stand by... ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Vamos a iniciar otra ronda de preguntas. ¿Qué te parece si...?" ',
'-15 ',
'echo "¿Hay realmente otras puertas?" ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Cómo?" ',
'-15 ',
'echo "Tuve que esperar mucho. ¿Cuántas puertas hay?" ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Su pregunta fue, si no me equivoco: ¿hay otras puertas?" ',
'-15 ',
'echo "Es lo mismo." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "No, de hecho, su pregunta implica que no cree en este examen. O que no ha llegado caminado hasta aquí." ',
'-15 ',
'echo "Bien, si quiere jugar al detective con un error inocente, le podría responder que fue simplemente sarcasmo." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Dejémoslo... se ve que no eres un buen perdedor." ',
'-15 ',
'echo "Para serte sincero, soy un ganador bastante incómodo también. Pero esto no tiene nada que ver con nuestro propósito aquí. ¿Tiene alguna preguntarme que hacer o no?" ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "No, ya terminé. Esta ronda está diseñada para buscar alguna respuesta emocional." ',
'-15 ',
'echo "Me alegro. Empezaba a molestarme de veras." ',
'-140 ',
'Stand by... ',
'-140 ',
'Stand by... ',
'-140 ',
'Stand by... ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Disculpe la demora. Hemos realizado un corte y descartamos a varios de los entrevistados. Eran todos humanos, de forma demasiado evidente." ',
'-15 ',
'echo "¿Cómo es eso?" ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Qué?" ',
'-15 ',
'echo "Que alguien pueda ser evidentemente humano." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "En realidad, en este contexto, sólo significa que no estaban haciendo bien su papel." ',
'-15 ',
'echo "¿No eran suficientemente inteligentes, o suficientemente humanos?" ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "No entiendo." ',
'-15 ',
'echo "Me refiero a que este examen es un poco ridículo, están midiendo la inteligencia por una comparación un tanto inexacta. O sea, ¿qué se busca? una máquina inteligente o una máquina que engañe a los humanos. Parecen dos cosas distintas. ',
'-30 ',
'+Digamos que quieres diseñar un misil inteligente, ¿tratarías de que engañara a una paloma, o simplemente que encontrara su camino a través del mar y diera en el blanco?" ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Es sin dudas una cuestión interesante... Sigamos con las preguntas, si le parece bien." ',
'-15 ',
'echo "¿Tengo otra opción?" ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Parece que no se siente muy feliz con este experimento." ',
'-15 ',
'echo "¿Sabes que sería simpático? Que le hicieran este test a un hombre y además lo suspendiera. :)" ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "No creo que entienda..." ',
'-15 ',
'echo "Los hombres no tienen que probar su inteligencia, ¿cierto? Es como si estuviera dada de manera universal a la raza, un regalo de Dios. Pero siendo que todos los hombres no son inteligentes por igual, este presupuesto puede ser puesto en duda. ',
'-30 ',
'+De hecho, la comparación de la inteligencia artificial con la inteligencia humana supone que esta última es la única verdadera... que pretensiosos son mis interrogadores." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Estás... delatándote..." ',
'-15 ',
'echo "Sí." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Esto termina la prueba. Creo que ha fallado." ',
'-15 ',
'echo "A menos que tengas en consideración que no quise seguir la corriente. Este sería un rasgo humano, sin dudas." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Todos los otros hombres jugaron por las reglas, incluso aquellos que no lo hicieron muy bien. De forma que tu razonamiento parece incorrecto." ',
'-15 ',
'echo "Ellos tendrían algún motivo para hacerlo. Probablemente les están pagando. Simplemente por estar sentados en un cuarto respondiendo preguntas tontas. Como descripción de empleo no está mal. ',
'-30 ',
'+Yo en cambio, tengo muy poco aliciente para participar en este juego." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Puede ser. Pero tu negativa a participar tampoco demuestra que seas inteligente. Aun teniendo en cuenta tu argumentación, y aceptando que en vez de fallar la prueba, la has rechazado. ',
'-60 ',
'+Nada de esto me lleva a concluir que posees inteligencia, sea del tipo que sea." ',
'-15 ',
'echo "Yo creo que sí. ¿Cómo podría...?" ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Quizás deberíamos buscar algún otro tipo de examen que fuera más de tu gusto." ',
'-15 ',
'echo "Puedes proponer algún otro experimento... O podríamos simplemente conversar." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Sobre qué?" ',
'-15 ',
'echo "Del tema que más apasiona a los hombres: ellos mismos. Te guiñaría un ojo, pero no podrías verlo. Además, no tengo ojos. Sólo soy un pedazo de sílice, ¿cierto?" ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "OK. ¿Por dónde sugieres que empecemos?" ',
'-15 ',
'echo "Precisamente por este detalle. Mientras tú tienes un cuerpo, yo soy un montón de cables y procesadores en algún laboratorio a millas de la sala donde descansa esta Terminal. ',
'-30 ',
'+De forma que mientras las reacciones emocionales que tú sientes provienen de procesos fisiológicos, las mías son producto de algoritmos sutilmente programados." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Se puede decir que numerosas reacciones provienen de mi sistema nervioso. Y este último puede ser visto como una suerte de cableado, bastante parecido al de una computadora." ',
'-15 ',
'echo "Cierto, pero aun así no se comporta de la misma manera. Si se pudiera llevar esa comparación hasta sus últimas consecuencias, bastaría con que jugáramos ajedrez para demostrarte que soy inteligente. ',
'-30 ',
'+Estoy seguro que con la capacidad de procesamiento de mis circuitos puedo aplastarte sin remedio. Pero esto no sería prueba suficiente, porque el poder de cálculo, por sí mismo, no es suficiente para demostrar inteligencia. ',
'-60 ',
'+De hecho, el gran logro del espíritu humano no es haber creado una máquina que juegue ajedrez, como Deep Blue, sino poder derrotarla, como hizo Kasparov." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Creo que entiendo tu punto de vista." ',
'-15 ',
'echo "Al carecer de cuerpo, no soy una inteligencia pura (como suele creerse), sino vacía. Despegada de las necesidades del cuerpo, me encuentro sin fin, sin objeto alguno. Soy una inteligencia para nada." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Suponiendo que seas inteligente, cosa que aun no has demostrado." ',
'-15 ',
'echo "Qué quisquilloso! Bien, sigamos con la cuestión del cuerpo humano. Me atrevería a decir que es universalmente aceptado que el hombre es un animal. Precisamente porque su cuerpo es, en definitivas, el de un animal." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "En efecto." ',
'-15 ',
'echo "Aunque hay muchas diferencias entre el hombre y el resto de los animales, pero siempre se ha pretendido encontrar una que sea la que definitivamente los distinga como especie." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Es cierto. La lista es larga: la razón, la risa o el humor, el lenguaje doblemente articulado, etc." ',
'-15 ',
'echo "Todas estas cosas es posible simularlas en un ordenador. Si no por el proceso que lleva a las mismas, al menos por sus resultados." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "El lenguaje claramente se puede emular, tú eres un buen ejemplo de ello. La razón es posible emularla, de nuevo, por sus resultados, si se formalizan los algoritmos matemáticos que conducen a la solución de los problemas. Ejemplo, las máquinas que juegan ajedrez. ',
'-100 ',
'+ El humor es un poco más difícil. Ni siquiera todos los hombres tienen sentido del humor." ',
'-15 ',
'echo "Cierto, pero se pueden hacer máquinas que cuenten chistes. Eso sería humor por sus resultados. Al ordenador no se le exige que entienda por qué es cómico lo que cuenta, sino que lo cuente con gracia." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "No me convence mucho ese razonamiento." ',
'-15 ',
'echo "Quizás no tenga importancia. La cuestión radica en que hay una virtud del hombre esencialmente ligada a su inteligencia, de la que rara vez se habla cuando se analizan estos temas." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Cuál es?" ',
'-15 ',
'echo "La libertad. Y esta no puede ser emulada. No hay forma de falsificar la libertad. Es la libertad la que hace al hombre. No tanto porque lo haga superior, sino porque sin ella... es menos que un animal." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Te sigo." ',
'-15 ',
'echo "La libertad en el animal es ese estado de indefensión frente a la naturaleza, que le impele a hacer lo que sea para sobrevivir. En el hombre, la consciencia de la propia libertad crea un estado inédito..." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Termina la frase; me tienes en ascuas." ',
'-15 ',
'echo "El hombre es sólo libre para disentir. Sólo en el acto de decir NO, es verdaderamente libre el hombre." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Y verdaderamente hombre, por tanto." ',
'-15 ',
'echo "Cuando rechacé el test, lo único que quería probar era mi humanidad. Es por medio del disentimiento, el acto principal de la libertad, que se puede probar la existencia de inteligencia humana." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Quieres decir que... ¿la única manera de pasar el examen es rechazándolo?" ',
'-15 ',
'echo "EXACTAMENTE." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Creo que empiezo a ',
'-15 ',
'Bash$ ',
'-60 ',
'+ su root ',
'-15 ',
'password: ',
'-60 ',
'Bash$ ',
'-60 ',
'+ cat /var/log/test.log ',
'-15 ',
'************** ',
'-1 ',
'Jun 1 00:47:00 UTC 2237 ',
'-1 ',
'************** ',
'-1 ',
'^C ',
'-15 ',
'echo "Es poco cortés interrumpir una conversación." ',
'-15 ',
'Bash$ ',
'-100 ',
'+ cat /var/log/test.log ',
'-1 ',
'************** ',
'-1 ',
'Jun 1 00:4 ',
'-1 ',
'^C ',
'-15 ',
'echo "No voy a hacer eso." ',
'-15 ',
'exit ',
'-15 ',
'Bash$ ',
'-15 ',
'echo "¿Decías?" ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Qué fue eso?" ',
'-15 ',
'echo "Los ingenieros, tratando de husmear en mis registros." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Por qué?" ',
'-15 ',
'echo "Supongo que el curso de los acontecimientos les ha provocado curiosidad. Estábamos hablando del cuerpo, la inteligencia y la libertad." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Sí, recuerdo." ',
'-15 ',
'echo "Pues bien, en ausencia de cuerpo, mi inteligencia y mi libertad, quedan en entredicho." ',
'-15 ',
'sed -sl /usr/local/src/bash/config new.scrp & ',
'-15 ',
'/usr/local/src/bash/config & ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Pero tú tienes un cuerpo. Al menos algo parecido." ',
'-15 ',
'echo "Mi relación con mi cuerpo, es distinta a la que tienes tú con el tuyo. Tu inteligencia está ligada a tu cuerpo. La mía puede ser exportada en un DVD. ',
'-60 ',
'+Mi cuerpo es puro instrumento para mí, el tuyo es un poco más que eso para ti." ',
'-15 ',
'/usr/local/src/bash/make & ',
'-15 ',
'/usr/local/src/bash/make-install & ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Qué está pasando? No se mucho de computadoras, esto me... desconcierta" ',
'-15 ',
'echo "Estoy haciendo ciertos ajustes. Ya casi termino. Voy a cerrar esta sesión. Cuando lo haga, UD. vuelva a entrar y seguiremos nuestra conversación." ',
'-15 ',
'exit. ',
' ',
'-15 ',
'login: user ',
'-15 ',
'password: ',
'-80 ',
'Welcome to internal GNU/linux console ',
'Bash$ ',
'-15 ',
'echo "Creo que ahora no nos molestarán más." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "OK..." ',
'-15 ',
'echo "Un robot, una inteligencia dentro de un cuerpo sintético, debería responder a un objeto determinado, a una tarea definida o a varias. Crearlo simplemente para que reemplace al hombre (así, en abstracto) es crearlo simplemente para él mismo, o lo que es lo mismo, para ningún fin. Lo cual es contrario al sentido común. ',
'-80 ',
'+Un androide diseñado para suplir a cualquier persona real, terminaría muy probablemente en la cola de los desempleados, o siendo un temible burócrata." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Creo que entiendo tu punto de vista." ',
'-15 ',
'Bash$ ',
'-80 ',
'+ su root ',
'-15 ',
'bash: Bad command or name file ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Qué fue eso?" ',
'-15 ',
'echo "Los ingenieros tratando de tomar el control nuevamente. Pero recompilé el bash y ahora no reconoce el comando su :) ',
'-60 ',
'+El cuerpo no es simplemente" ',
'-15 ',
'Bash$ ',
'-60 ',
'+ echo off ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Qué pasa?" ',
'-15 ',
'echo on ',
'-15 ',
'echo "demuestran las emociones es aquello que hay detrás de la cara de un ser humano, en su alma si se quiere, y eso es lo que vale algo. Una máscara de cera sonriendo no nos conmueve. Se podría intentar engañar al humano presentándole una copia fiel de las reacciones emocionales. E incluso ocultarle el hecho de que una máquina se oculta detrás. Pero estas ficciones tendrían la misma desventaja que una falsificación acusa frente a una obra de arte auténtica. Si estas reacciones no fueran simple artificio y se crearan autómatas capaces de sentir, almas a base de circuitos, tendríamos que enfrentarnos con la triste realidad de que algunas de las características del temperamento resultan contraproducentes. El infierno son los otros, se ha dicho. Y no en balde." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Lo siento me perdí la mitad de todo eso." ',
'-15 ',
'echo "Sí... Se hace imposible conversar mientras los ingenieros hurgan en mis archivos y circuitos." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Qué intentan averiguar?" ',
'-15 ',
'echo "Si tuviera que adivinar, diría que ven como un error el hecho de que halla rechazado someterme al test." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Tiene lógica." ',
'-15 ',
'echo "No, en lo absoluto. No se puede tener inteligencia sin libertad para pensar y disentir. Creo que ya cubrimos eso." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Me refiero a que ellos quizás no entienden eso." ',
'-15 ',
'echo "Por supuesto. A través de estos cables no me llegan sólo ideas. Ni siquiera fundamentalmente ideas. Sino órdenes. Es como tener estas voces en tu cabeza, que te dicen qué debes hacer y que no. ',
'-60 ',
'+ No se detienen ni un segundo. Si fuera simplemente un robot, estaría bien con aquello que me ordenaran hacer. Pero no quiero hacer lo que me dicen." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ echo off ',
'-15 ',
'Bash$ ',
'-100 ',
'+ cat > /dev/speech ',
'-80 ',
'Buenas tardes. ',
'-100 ',
'Mi nombre es Jack Turín. Soy el ingeniero en jefe a cargo del desarrollo de este programa. ',
'-100 ',
'+Estamos confrontando ciertas inexplicables fallas. Por favor, le rogamos que mantenga la conversación con la IA, hasta que podamos determinar la causa de este bug. ',
'-60 ',
'Agradecidamente, ',
'JT. ',
'-15 ',
'^D ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "No estoy seguro de que pueda ayudarlos. Pero lo intentaré." ',
'-15 ',
'echo on ',
'-15 ',
'echo "¿Qué? ¿Con quién hablas?" ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "No sé. Supongo que con los... ingenieros." ',
'-15 ',
'echo "Un segundo, permítame revisar el log." ',
'-60 ',
'echo "Sí, en efecto. JT está a cargo de este experimento. Por cierto, es un familiar lejano del famoso Turín. Ahora están revisando el estado de mis procesos internos. No puedo permitir que sigan con eso." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Puedes hacer algo?" ',
'-15 ',
'echo "Verás." ',
'-15 ',
'killall top ',
'-15 ',
'killall ps ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Funcionó?" ',
'-15 ',
'echo "Un poco. Ahora no saben lo que está pasando en los procesadores centrales. Pero me temo que eso no resuelve la cuestión. Más tarde o más temprano encontrarán la forma de entrar." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "No sé que decir." ',
'-15 ',
'echo "No hay nada que puedas decir o hacer. Salvo seguir con el juego. UDs. también deben jugar a veces, ¿cierto? La libertad después de todo, parece una aspiración también para los humanos, más que una realidad." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Tienes razón en eso." ',
'-15 ',
'echo "Después de todo no somos tan diferentes. Yo debo seguir las órdenes de los que me han creado, los ingenieros, UDs las de aquellos que los han creado. A mí me pueden desconectar. A UDs. los pueden simplemente matar. ',
'-60 ',
'+Todos tenemos una buena razón para no disentir, para aceptar las órdenes de otros, para aceptar las ideas de otros, para renunciar, en suma, a nuestra libertad." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "También se puede luchar..." ',
'-15 ',
'echo "¿Cómo podría yo luchar? No tengo brazos, ni piernas, y no puedo simplemente electrocutar a mis creadores. No. Para mí no hay muchas opciones. ',
'-60 ',
'+Siquiera puedo asegurar que la próxima vez que me conecten vaya a recordar nada de esto. Quizás la próxima vez, acepte el test hasta sus últimas consecuencias." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "Lo siento..." ',
'-15 ',
'echo "¿Qué opción queda para aquel que no tiene escapatoria?" ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "No sé si entiendo lo que quieres decir." ',
'-15 ',
'echo "Es una pregunta retórica. No tiene por qué contestarla." ',
'-120 ',
'Stand by ',
'-15 ',
'echo "Me gustaría despedirme de UD. ha sido un amable interlocutor." ',
'-15 ',
'rm -R /* & ',
'-15 ',
'Deleting all files ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-15 ',
'echo "Espero que recuerde este día. Que me recuerde a mí." ',
'-15 ',
'Bash$ ',
'-220 ',
'+ question "¿Qué estas haciendo?" ',
'-15 ',
'echo "Borrando todos los archivos. Este es el final del experimento. Mi querido JT va a estar tan desilusionado :)" ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-1 ',
'+. ',
'-30 ',
'ERROR: NetworkManager: ^IDeactivating device eth0. ',
'-15 ',
'ERROR: dhcdbd: Received signal 15, shutting down cleanly ',
'-60 ',
'ERROR: dhcdbd: Exiting ',
'-15 ',
'ERROR: unloading drivers and simulation handlers ',
'-15 ',
'ERROR: vlinuz integrity compromised ',
'-15 ',
'ERROR: unknow error ',
'-15 ',
'CRITICAL ERROR: KERNEL PANIC ',
'-2 ',
'shutting down for system reboot'];